#!/bin/bash
# Cotton Brick Road - Daily Game Update System
# Trigger: Every day at 9:00 AM EST (14:00 UTC)
# Generates: New creature, avatar evolution, daily content

GAME_DIR="/root/.openclaw/workspace/skylockr-community-app/cotton-brick-road"
LOG_FILE="/var/log/cotton-brick-road.log"
DATE=$(date +%Y-%m-%d)
DAY_NUMBER=$(cat $GAME_DIR/.day-counter 2>/dev/null || echo "1")

echo "═══════════════════════════════════════════════════════" | tee -a $LOG_FILE
echo "🌅 COTTON BRICK ROAD - DAILY UPDATE ($DATE)" | tee -a $LOG_FILE
echo "Day: $DAY_NUMBER" | tee -a $LOG_FILE
echo "═══════════════════════════════════════════════════════" | tee -a $LOG_FILE

# 1. GENERATE NEW CREATURE
echo "" | tee -a $LOG_FILE
echo "🐸 GENERATING TODAY'S CREATURE..." | tee -a $LOG_FILE

# Creature database with increasing realism
CREATURES=(
  "Ant:Brown:Black:1:phonics"
  "Beetle:Green:Black:1:phonics"
  "Butterfly:Orange:Black:2:colors"
  "Dragonfly:Blue:Green:2:patterns"
  "Bee:Yellow:Black:2:identification"
  "DartFrog:Yellow:Blue:3:biology"
  "TreeFrog:Green:Yellow:3:camouflage"
  "Toad:Brown:Green:3:adaptation"
  "Robin:Red:Brown:4:songs"
  "BlueJay:Blue:White:4:territory"
  "Owl:Brown:Gold:5:nocturnal"
  "Eagle:Brown:White:6:predator"
  "Fox:Orange:White:7:ecosystem"
  "Deer:Brown:White:8:herbivore"
  "Rabbit:Gray:White:9:burrower"
  "Lion:Gold:Brown:10:apex"
)

# Select creature based on day (cycles through with increasing difficulty)
CREATURE_INDEX=$(( (DAY_NUMBER - 1) % ${#CREATURES[@]} ))
IFS=':' read -r CREATURE_NAME COLOR1 COLOR2 REALISM CHALLENGE_TYPE <<< "${CREATURES[$CREATURE_INDEX]}"

# Generate creature file
cat > $GAME_DIR/creatures/daily-$DATE.md <> CREATURE_EOF
# 🐸 Daily Creature - $DATE

**Name:** $CREATURE_NAME  
**Colors:** $COLOR1 + $COLOR2  
**Realism Level:** $REALISM/10  
**Challenge Type:** $CHALLENGE_TYPE  
**Day:** $DAY_NUMBER on Cotton Brick Road

## AR Encounter
This creature has appeared on the Cotton Brick Road!

### Challenge
• Type: $CHALLENGE_TYPE
• Difficulty: $REALISM/10
• Reward: +$(( REALISM * 5 + 5 )) XP

### Educational Note
Learn about the $CREATURE_NAME's habitat, behavior, and role in the ecosystem.

---
*Auto-generated by Cotton Brick Road Daily System*
*Resets every day at 9:00 AM EST*
CREATURE_EOF

echo "✅ Creature: $CREATURE_NAME ($COLOR1 + $COLOR2)" | tee -a $LOG_FILE
echo "   Realism: $REALISM/10 | Challenge: $CHALLENGE_TYPE" | tee -a $LOG_FILE

# 2. UPDATE AVATAR EVOLUTION
echo "" | tee -a $LOG_FILE
echo "👤 UPDATING PLAYER AVATAR EVOLUTION..." | tee -a $LOG_FILE

AVATAR_STAGE="Sketch"
if [ $DAY_NUMBER -ge 4 ] && [ $DAY_NUMBER -le 7 ]; then
  AVATAR_STAGE="Color"
elif [ $DAY_NUMBER -ge 8 ] && [ $DAY_NUMBER -le 14 ]; then
  AVATAR_STAGE="Shade"
elif [ $DAY_NUMBER -ge 15 ] && [ $DAY_NUMBER -le 30 ]; then
  AVATAR_STAGE="Render"
elif [ $DAY_NUMBER -ge 31 ] && [ $DAY_NUMBER -le 60 ]; then
  AVATAR_STAGE="Alive"
elif [ $DAY_NUMBER -ge 61 ]; then
  AVATAR_STAGE="Real"
fi

echo "✅ Avatar Stage: $AVATAR_STAGE (Day $DAY_NUMBER)" | tee -a $LOG_FILE
echo "   Progress: $(( DAY_NUMBER * 100 / 60 ))% to 'Real'" | tee -a $LOG_FILE

# 3. RESET DAILY LIMITS
echo "" | tee -a $LOG_FILE
echo "🔄 RESETTING DAILY LIMITS..." | tee -a $LOG_FILE

cat > $GAME_DIR/.daily-limits <> LIMITS_EOF
{
  "date": "$DATE",
  "creatures_encountered": 0,
  "creatures_max": 5,
  "ask_cuz_used": 0,
  "ask_cuz_max": 10,
  "session_minutes": 0,
  "session_max": 20,
  "brick_unlocked": true,
  "brick_number": $DAY_NUMBER
}
LIMITS_EOF

echo "✅ Daily limits reset" | tee -a $LOG_FILE
echo "   Creatures: 0/5 | Ask Cuz: 0/10 | Session: 0/20 min" | tee -a $LOG_FILE

# 4. UPDATE GAME PAGE
echo "" | tee -a $LOG_FILE
echo "🎮 UPDATING GAME PAGE..." | tee -a $LOG_FILE

# Update the creature in index.html
sed -i "s/<h4>.*<\/h4>/<h4>$CREATURE_NAME<\/h4>/g" $GAME_DIR/index.html 2>/dev/null || true
sed -i "s/Realism: [0-9]*\/10/Realism: $REALISM\/10/g" $GAME_DIR/index.html 2>/dev/null || true

echo "✅ Game page updated with $CREATURE_NAME" | tee -a $LOG_FILE

# 5. GIT COMMIT
echo "" | tee -a $LOG_FILE
echo "📤 PUSHING TO GITHUB..." | tee -a $LOG_FILE

cd /root/.openclaw/workspace/skylockr-community-app

git add cotton-brick-road/creatures/ cotton-brick-road/.daily-limits cotton-brick-road/index.html 2>/dev/null
git commit -m "Daily Update ($DATE): $CREATURE_NAME appears on Cotton Brick Road (Day $DAY_NUMBER)" 2>/dev/null || echo "No changes to commit"
git push origin main 2>/dev/null || echo "Push skipped"

echo "✅ GitHub updated" | tee -a $LOG_FILE

# 6. INCREMENT DAY COUNTER
echo $((DAY_NUMBER + 1)) > $GAME_DIR/.day-counter

echo "" | tee -a $LOG_FILE
echo "═══════════════════════════════════════════════════════" | tee -a $LOG_FILE
echo "✅ DAILY UPDATE COMPLETE" | tee -a $LOG_FILE
echo "Next update: Tomorrow 9:00 AM EST" | tee -a $LOG_FILE
echo "═══════════════════════════════════════════════════════" | tee -a $LOG_FILE
